### ISSUE TITLE
Cached time from external time providers

### ISSUE THREAD

**Issue by zzanzare** [RobThree/TwoFactorAuth#20]
I tried the demo and noticed that for the first time it ran correctly, but then after refresh it started complaining about mismatched times from convert-unix-time.com. I tracked it down to the request to the external website being cached. To prevent caching in curl you can add header Cache-Control: no-cache (https://stackoverflow.com/a/36043573/4088846) or add a random suffix to the url when calling file_get_contents (https://stackoverflow.com/a/21755086/4088846). Why are you not reusing the part from HttpTimeProvider anyway?

**Comment by RobThree** [comment]
> Why are you not reusing the part from HttpTimeProvider anyway?

Because the `HttpTimeProvider`'s method is to extract a `Date:` header from the response and use that time; the `ConvertUnixTimeDotComTimeProvider` uses the responsebody (which is JSON) to retrieve the time.

As far as I can see, `file_get_contents()` **shouldn't** use any caching but is, [apparently](https://bugs.php.net/bug.php?id=36555), bugged. I'll fix this soon; probably by simply adding a random string to the URl which is the easiest (and most reliable) fix I think.

**Comment by webguy1** [comment]
@RobThree Has or will this issue be resolved, or has this project been discontinued?

**Comment by RobThree** [comment]
It will be resolved; this project hasn't been discontinued. I am currently busy recovering from a quite unexpected hospitalisation but as soon as I get around to it I will fix this. Promised.

**Comment by RobThree** [comment]
See b1ecc9afbcd379bb12db0422fc6e67eafe84f9ff
