### ISSUE TITLE
verifyCode trouble

### ISSUE THREAD

**Issue by qcmarcel** [RobThree/TwoFactorAuth#33]
Hi, RobThree

I actually implement TwoFactorAuth on my PHP project.

I debug the QRcode & secret in my phone via Google Authenticator and response good.

The problem is when I want to validate code.  I create a input field that capture value but not matches.

see more details : https://imgur.com/EDqzVes

you can check my project : https://github.com/networksoft/erp.playerbitcoin

Hope your Orientation. 

thanks.

**Comment by RobThree** [comment]
First thing to check: [are you sure your time is correct](https://github.com/RobThree/TwoFactorAuth/blob/7477d5d65625b7fe33cb338b98e419d394e9e9fd/demo/demo.php#L28)? Second; don't point people to your source/project. Provide (relevant!) code in the issue itself instead of saying: _"here's my code, you figure it out!"_. So please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).

**Comment by qcmarcel** [comment]
hi, I've verified thst my time is correct.

Please enter in this site: https://mesadejuego.playerbitcoin.com
username 2 password Qnh6rIekdd

next type in url /ov/networkprofile/profile & enter

and click on secret field, paste this : 1069740663

hope your attention

thanks

**Comment by RobThree** [comment]
> next type in url /ov/networkprofile/profile & enter

I'm getting:

<pre>Fatal error: Class 'CI_Controller' not found in /home/playerbitcoin/erp.playerbitcoin/system/core/CodeIgniter.php on line 233</pre>

But this is not what an [MCVE](https://stackoverflow.com/help/mcve), which is what I asked for, is.

Also: I don't understand why you think that telling me the secret (`1069740663`, which is usually only 6 digits but OK) would work? The secret changes at regular intervals? Are you sure you understand how a [TOTP works](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm)?

Anyway; I can't see the problem since the page gives me an error anyway. Again; please provide an MCVE; don't send me instructions which site to visit and what to click/do/enter. That isn't helpful.

**Comment by RobThree** [comment]
Ok, I shouldn't be dong this nor should I be required to put this much effort in but I found out that the page should be: /ov/network**P**rofile/profile

I got to enter the secret ONCE (which turned out not to be a TOTP code but a code to 'reset' the 2FA I guess) and I then got a QR code which I could scan & verify fine. However, I couldn't try a second time because now each time I click the secret field I get a pop-up "PLEASE ENTER CORRECT SECRET FOR RESET!!!" before I can even enter the secret.

Again; this shouldn't be this hard. You can't expect people to go through this much trouble and jump through _your_ hoops trying to help you. **You** need help. Then **help me help you**. Make it as easy as possible for me to help you.

**Comment by qcmarcel** [comment]
Hi.

I've verified that my time is correct.

Please explain (or better: show) how you verified this. Did you call the ensureCorrectTime() method?

R: YES I DO IT.

Ok, I shouldn't be doing this nor should I be required to put this much effort in but I found out that the page should be:

/ov/networkProfile/profile

R: please try again.

**Comment by RobThree** [comment]
No this isn't going to work. Please read my comments again and open a new issue that follows the instructions that I provided in the comments (at the very least an MCVE).
