### ISSUE TITLE
Exception when code type is integer (expected string)

### ISSUE THREAD

**Issue by Zaczero** [RobThree/TwoFactorAuth#38]
### Actual behavior
While passing `code` parameter to `verifyCode` function and the `code` parameter is integer type the function crashes.

### Expected behavior 
`verifyCode` function verifies the `code` which is provided as integer.

### Code to reproduce
```php
$tfa = new RobThree\Auth\TwoFactorAuth("TEST");
$tfa->verifyCode("USJNHRTSCEAY2OME6IB7CLEE6HACYQGN", 123123);
```

![](https://i.imgur.com/M4nQszS.png)
![](https://i.imgur.com/AUdszPq.png)

### Workaround
```php
$tfa = new RobThree\Auth\TwoFactorAuth("TEST");
$tfa->verifyCode("USJNHRTSCEAY2OME6IB7CLEE6HACYQGN", (string) 123123);
```

#### Edit.

In case of the `code` starting by 0 the `verifyCode` function should prepend missing zeros based on the code generation length or drop the leading zeros from internal code generation. OR maybe just switch completely to integers as working with them is faster than strings *= less cpu ticks = less co2 emission* 🚭

**Comment by RobThree** [comment]
Uh, no. The code is, and should be, a string. Just because it only contains numbers doesn't make it an integer. You already discovered that leading zeroes will become a problem. Just like a phonenumber (which also, usually, only contains numbers) is a string, this verification code is supposed to be a string as well.

If anything, I should probably add typehinting someday and ensure all arguments are of the correct type.
