### ISSUE TITLE
Timing attack

### ISSUE THREAD

**Issue by Pollux42** [RobThree/TwoFactorAuth#55]
I have a theoretical question about this snippet of code:

```
        // To keep safe from timing-attacks we iterate *all* possible codes even though we already may have
        // verified a code is correct. We use the timeslice variable to hold either 0 (no match) or the timeslice
        // of the match. Each iteration we either set the timeslice variable to the timeslice of the match
        // or set the value to itself.  This is an effort to maintain constant execution time for the code.
        for ($i = -$discrepancy; $i <= $discrepancy; $i++) {
            $ts = $timetamp + ($i * $this->period);
            $slice = $this->getTimeSlice($ts);
            $timeslice = $this->codeEquals($this->getCode($secret, $ts), $code) ? $slice : $timeslice;
        }

        return $timeslice > 0;
```

I wonder if the iteration of *all* possible code is really needed to keep safe from timing attack.
Eventually, if we do early return as soon as a code is correct, the only leaked information is the number of time slice checked.
What do you think?

**Comment by RobThree** [comment]
It's a remote (if at all) chance in this particular case, but timing side-channel attacks are very real. It's a small effort to sidestep it with this code, why not do it? It's the reason `hash_equals` exists. The 'early exit' would save us from a 'few' CPU cycles but I think that would be a micro-optimisation.

**Comment by Pollux42** [comment]
Precisely, I would like to know, in this particular case, if that small effort is done to have peace of mind (given the micro-optimization may not worth it), or if there is an identified exploit that could use the leak of that particular information.

It's like the comment in the codeEquals function: 
```
        // In general, it's not possible to prevent length leaks. So it's OK to leak the length. The important part is that
        // we don't leak information about the difference of the two strings.
```

So it seems to be OK to leak the length. Maybe would it be OK to leak "the number of slices checked"? (regardless of the motivation do the micro-optimization)

**Comment by RobThree** [comment]
It's ok to leak the length since we can assume any attacker knows the length anyway (they could simply create an account and see what kind of codes they get). Also, the number of possible (realistic) lengths is limited to just a handful.

> Maybe would it be OK to leak "the number of slices checked"?

It won't be horrible if it was leaked, but, in general, you try to leak as little as possible. For the length there's no real solution (padding it to a fixed length wouldn't help since the padding itself would take a measurable amount of difference in time for each length) but for the number of slices we can easily check them all and make the operation constant time.

Out of curiosity: Why are you asking? What is it that you're after?

**Comment by Pollux42** [comment]
It's just a question from a curious (and maybe pedantic?) developer.
Thank you for your time and for the answer, it's clear to me.
